# For settings, refer to `https://qiita.com/delphinus/items/cd221a450fd23506e81a`   

[[plugins]]
repo = "w0ng/vim-hybrid"

[[plugins]]
repo = "itchyny/lightline.vim"

[[plugins]]
repo = "dhruvasagar/vim-table-mode"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
# original.  
# repo = "jpalardy/vim-slime"
# You must not set `let g:slime_python_ipython = 0`.

repo = "sillte/vim-slime"
hook_add = """
let g:slime_vimterminal_cmd = "ipython"
let g:slime_target = "vimterminal"
xmap <leader>f <Plug>SlimeRegionSend
nmap <leader>f <Plug>SlimeParagraphSend
"""

[[plugins]]
repo = "cespare/vim-toml"

# Python's related libraries.  
[[plugins]]
repo = "davidhalter/jedi-vim"
hook_add = """
let g:jedi#rename_command = "<Leader>R"
let g:jedi#auto_initializtion = 0
let g:jedi#completion_enabled = 0
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
"""

[[plugins]]
repo = "psf/black"

[[plugins]]
repo = "sillte/vim-pytoy"
hook_add = """
call pytoy#init_python()
"""
