[[plugins]]
repo = "davidhalter/jedi-vim"
hook_source = """
let g:jedi#rename_command = "<Leader>R"
let g:jedi#auto_initializtion = 0
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
"""

[[plugins]]
repo = "w0ng/vim-hybrid"

[[plugins]]
repo = "itchyny/lightline.vim"

[[plugins]]
repo = "dhruvasagar/vim-table-mode"

[[plugins]]
repo = "psf/black"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "sillte/vim-pytoy"
hook_post_source = """
call pytoy#init_python()
"""

# Notice that  ``hook_add`` is applied immediately. 
# If you use  ``_plugins`` folder (Personal plugins for development, 
# you should not use `hook_add`. 
