" File Structures
" ------------
" [IMPORTANT] When you transport the environment, `.vim` should  also be
" transported.
"
" ============================================================================
" Environment
" ============================================================================
set encoding=utf8
set fileencoding=utf8
scriptencoding utf-8
let s:myvim_folder = expand('<sfile>:p:h') . "/.vim"  

if exists('$XDG_CACHE_HOME')
    let s:cache = $XDG_CACHE_HOME . '/vim'
else
    let s:cache = expand('~/.cache/vim')
endif


" ============================================================================
" Utility functions
" ============================================================================

function! s:SourceIfExists(path) abort
    if filereadable(a:path)
        execute 'source' fnameescape(a:path)
    endif
endfunction

function! s:AddRuntime(path) abort
    if isdirectory(a:path)
        execute 'set runtimepath^=' . fnameescape(a:path)
    endif
endfunction    


" ============================================================================
" Options
" ============================================================================

syntax enable

set number
set signcolumn=yes
set laststatus=2

set winaltkeys=no

set shellslash
set helplang=en,jp

set tabstop=8 expandtab shiftwidth=4 softtabstop=4
set smartindent

set hidden
set visualbell t_vb=
set noerrorbells 
set clipboard+=unnamed
set backspace=start,eol,indent

" ============================================================================
" Keymaps
" ============================================================================

"When you leave insert mode, always `IM` becomes off.
inoremap <ESC> <ESC>:set iminsert=0<CR>  

nnoremap j gj
nnoremap k gk

inoremap jj <ESC>

" Moving between buffers, tabs, windows.
nnoremap [b :bnext<CR>
nnoremap ]b :bprevious<CR>
nnoremap [t :tabnext<CR>
nnoremap ]t :tabprevious<CR>
nnoremap [l :lnext<CR>
nnoremap ]l :lprevious<CR>
nnoremap [w <C-W><C-W>
nnoremap ]w <C-W><C-P>
noremap <F2> :execute ":edit " . $MYVIMRC <CR>
noremap <F3> :execute ":edit " . s:myvim_folder <CR>

" ============================================================================
" Initialization 
" ============================================================================

function! s:InitCache() abort
    call mkdir(s:cache, 'p')

    set undofile
    set undolevels=10000
    set undoreload=100000

    let &undodir = s:cache . '/undo'
    call mkdir(&undodir, 'p')

    set nobackup
    set nowritebackup
    set noswapfile
endfunction

" Initialization of cache
call s:InitCache()

" Site-specific configuration
call s:SourceIfExists(s:myvim_folder . "/site.vim")
" Experimental scripts
call s:SourceIfExists(s:myvim_folder . "/scratch.vim")

" ============================================================================
" Plugin Setup
" ============================================================================

" Sandbox plugins.
let s:myplugins_init = fnameescape(s:myvim_folder . "/_myplugins/init.vim")
execute "source" s:myplugins_init


"Debug script for `pytoy`.
call s:SourceIfExists(s:myvim_folder . "/pytoy_debug.vim")
if exists('*OverridePytoyRuntime')
    call OverridePytoyRuntime(s:cache)
endif


call s:SourceIfExists(s:myvim_folder . "/dein.vim")   
call s:SourceIfExists(s:myvim_folder . "/lsp.vim")   


" ============================================================================
" Hack
" ============================================================================
"I am not able to detect the reason yet,  
"however, in 2025, Oct, `filetypes` is not loaded... 
"Therefore, this is the counter-measure.
if exists("did_load_filetypes") == 0
  runtime! filetype.vim
endif

filetype plugin indent on
